maintainerr:
  ingress:
    main:
      enabled: true
      hosts:
        - host: maintainerr.homelab.fouad.dev

  workload:
    main:
      podSpec:
        containers:
          main:
            env:
              TELEMETRY: "off"

  persistence:
    data:
      enabled: false
    data-ng:
      enabled: true
      type: pvc
      storageClass: longhorn
      mountPath: "/opt/data"
      size: 500Mi

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
