# Quality definitions from the guide to sync to Sonarr. Choices: series, anime
quality_definition:
  type: series
# Quality Profile Configuration
quality_profiles:
  - name: DEFAULT
    reset_unmatched_scores:
      enabled: false
    upgrade:
      allowed: true
      until_quality: 1080p
      until_score: 10000
    min_format_score: 0
    quality_sort: top
    qualities:
      - name: 1080p
        qualities:
          - WEBDL-1080p
          - WEBRip-1080p
          - Bluray-1080p
          - HDTV-1080p
      - name: 720p
        qualities:
          - WEBDL-720p
          - WEBRip-720p
          - Bluray-720p
          - HDTV-720p
# Set to 'true' to automatically remove custom formats from Sonarr when they are removed from
# the guide or your configuration. This will NEVER delete custom formats you manually created!
delete_old_custom_formats: true
custom_formats:
  # A list of custom formats to sync to Sonarr.
  # Use `recyclarr list custom-formats sonarr` for values you can put here.
  # https://trash-guides.info/Sonarr/Sonarr-collection-of-custom-formats/
  - trash_ids:
      - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups (-10000)
      - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ (-10000)
      - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release Title) (-10000)
      - 23297a736ca77c0fc8e70f8edd7ee56c # Upscaled (-10000)
      - fbcb31d8dabd2a319072b84fc0b7249c # Extras (-10000)
    assign_scores_to:
      - name: DEFAULT
      - name: BLURAY
      - name: REMUX
      
  - trash_ids:
      - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01 (1700)
      - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02 (1650)
      - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03 (1600)

      - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper (5)
      - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2 (6)
      - 44e7c4de10ae50265753082e5dc76047 # Repack v3 (7)

      - 505d871304820ba7106b693be6fe4a9e # HDR (500)
      - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost (100)
      - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost (1000)
      - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback) (-10000)
    assign_scores_to:
      - name: DEFAULT
      - name: BLURAY
      - name: REMUX
      - name: Any

  - trash_ids:
      - 63487786a8b01b7f20dd2bc90dd4a477 # DD+ (1750)
    assign_scores_to:
      - name: DEFAULT
        score: 125
  - trash_ids:
      - 4232a509ce60c4e208d13825b7c06264 # DD+ ATMOS (3000)
      - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD) (-10000)
    assign_scores_to:
      - name: DEFAULT
        score: 135
  - trash_ids:
      - 7ba05c6e0e14e793538174c679126996 # Multi (N/A)
      - 2c29a39a4fdfd6d258799bc4c09731b9 # VFF (N/A)
    assign_scores_to:
      - name: DEFAULT
        score: 10
      - name: BLURAY
        score: 10
      - name: REMUX
        score: 10
      - name: Any
        score: 10
