#SPDX-License-Identifier: MIT-0
---
# tasks file for linstor

- name: Add LINBIT APT Repository
  ansible.builtin.deb822_repository:
    name: linbit
    types: deb
    uris: http://packages.linbit.com/public/
    suites: proxmox-9
    components: drbd-9
    signed_by: https://packages.linbit.com/package-signing-pubkey.asc

- name: Install low level components
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - proxmox-headers-{{ ansible_kernel }}
      - drbd-dkms
      - drbd-utils
      - resource-agents
      - nfs-common
      - nfs-kernel-server

- name: Install LINSTOR components
  ansible.builtin.apt:
    state: present
    name:
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - linstor-controller=1.35.2-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - linstor-satellite=1.35.2-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - linstor-client=1.27.1-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - linstor-proxmox=8.2.1-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - linstor-gui=2.4.0-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - drbd-reactor=1.11.0-1
      # renovate: registry=https://packages.linbit.com/public suite=proxmox-9 components=drbd-9
      - thin-send-recv=1.1.3-1

- name: Prevent packages from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - linstor-controller
    - linstor-satellite
    - linstor-client
    - linstor-proxmox
    - linstor-gui
    - drbd-reactor

- name: Disable NFS Kernel Server service
  ansible.builtin.systemd_service:
    name: nfs-kernel-server
    state: stopped
    enabled: false

- name: Ensure Linstor Sattelite service dir exists
  ansible.builtin.file:
   path: /etc/systemd/system/linstor-satellite.service.d
   state: directory

- name: Configure LINSTOR Satellite service
  ansible.builtin.copy:
    dest: /etc/systemd/system/linstor-satellite.service.d/override.conf
    mode: '0644'
    content: |
      [Service]
      Type=notify
      TimeoutStartSec=infinity
      Environment=LS_KEEP_RES=linstor_db
  notify: (Re)Start LINSTOR satellite service

- name: Configure LINSTOR Satellite
  ansible.builtin.template:
    src: "linstor_satellite.toml.j2"
    dest: "/etc/linstor/linstor_satellite.toml"
  notify: (Re)Start LINSTOR satellite service

- name: Stop LINSTOR controller service
  ansible.builtin.systemd_service:
    name: linstor-controller
    state: stopped
    enabled: false # DRBD Reactor will manage this service

- name: Linstor DB mount service
  ansible.builtin.template:
   src: var-lib-linstor.mount.j2
   dest: /etc/systemd/system/var-lib-linstor.mount
  notify: Reload systemd

- name: Ensure DRBD volume is unmounted via systemd
  delegate_to: pve_0
  ansible.builtin.systemd_service:
    name: var-lib-linstor.mount
    state: stopped

- name: Ensure mount point directory
  ansible.builtin.file:
    path: /var/lib/linstor
    state: directory
    mode: '0750'
    attributes: +i # Set immutable flag on mount point (LINSTOR >= 1.14.0)

- name: Promote DRBD resource to Primary
  delegate_to: pve_0
  command: "drbdadm primary linstor_db"
  register: drbd_primary
  changed_when: "'already Primary' not in drbd_primary.stderr"

- name: Create ext4 filesystem on DRBD device
  delegate_to: pve_0
  ansible.builtin.filesystem:
    fstype: ext4
    dev: "/dev/drbd/by-res/linstor_db/0"

- name: Ensure DRBD volume is mounted via systemd
  delegate_to: pve_0
  ansible.builtin.systemd_service:
    name: var-lib-linstor.mount
    state: started
    enabled: false # DRBD Reactor will manage this service

- name: Enable LINSTOR controller service on one node only
  delegate_to: pve_0
  ansible.builtin.systemd_service:
    name: linstor-controller
    state: started
    enabled: false # DRBD Reactor will manage this service

- name: DRBD promoter config file
  ansible.builtin.template:
    src: "linstor_db.toml.j2"
    dest: "/etc/drbd-reactor.d/linstor_db.toml"
  notify: (Re)Start DRBD Reactor service

- name: Create symbolic links for drbd-reactor reload units
  ansible.builtin.file:
    src: "/usr/share/doc/drbd-reactor/examples/drbd-reactor-reload.{{ item }}"
    dest: "/etc/systemd/system/drbd-reactor-reload.{{ item }}"
    state: link
    force: yes
  loop:
    - path
    - service
  notify:
    - Reload systemd
    - (Re)Start DRBD Reactor Reload service

- name: Download and install the linstor-gateway binary
  tags:
    - linstor_gw
  ansible.builtin.get_url:
    url: https://github.com/LINBIT/linstor-gateway/releases/download/v2.0.0/linstor-gateway-linux-amd64
    dest: /usr/sbin/linstor-gateway
    mode: '0755'

- name: Ensure Linstor Gateway Server config directory
  tags:
    - linstor_gw
  ansible.builtin.file:
    path: /etc/linstor-gateway
    state: directory

- name: Configure the LINSTOR Gateway service
  tags:
    - linstor_gw
  ansible.builtin.template:
   src: linstor-gateway.toml.j2
   dest: /etc/linstor-gateway/linstor-gateway.toml

- name: Install Linstor Gateway Server service
  tags:
    - linstor_gw
  ansible.builtin.template:
   src: linstor-gateway.service.j2
   dest: /etc/systemd/system/linstor-gateway.service
  notify: Reload systemd

- name: Enable Linstor Gateway Server service
  tags:
    - linstor_gw
  ansible.builtin.systemd_service:
    name: linstor-gateway
    state: started
    enabled: true
