homebridge:
  podOptions:
    hostNetwork: true

  ingress:
    main:
      enabled: true
      hosts:
        - host: homebridge.homelab.fouad.dev

  persistence:
    config:
      type: pvc
      storageClass: longhorn
      size: 1Gi
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
        argocd.argoproj.io/sync-options: Delete=false

  resources:
    requests:
      cpu: 75m
      memory: 200Mi
    limits:
      cpu: 1500m
      memory: 1024Mi
